# Generated by Django 4.2.1 on 2023-05-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('type', models.CharField(blank=True, max_length=250, null=True)),
                ('domesticity', models.CharField(blank=True, max_length=250, null=True)),
                ('registered_agent', models.CharField(blank=True, max_length=250, null=True)),
                ('date_formed', models.CharField(blank=True, max_length=20, null=True)),
                ('duration', models.CharField(blank=True, max_length=250, null=True)),
                ('renewal_month', models.CharField(blank=True, max_length=50, null=True)),
                ('report_due', models.CharField(blank=True, max_length=20, null=True)),
                ('chapter', models.CharField(blank=True, max_length=250, null=True)),
                ('home_state', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('link', models.CharField(max_length=250, unique=True)),
            ],
            options={
                'verbose_name': 'Info',
                'verbose_name_plural': 'Info',
            },
        ),
    ]
