# Generated by Django 4.2.1 on 2023-05-22 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0004_keys'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keys',
            new_name='Keys_w',
        ),
    ]
